version: "2"

services:
  docker-web:
    image: klausmeyer/docker-registry-browser
    container_name: docker-web
    environment:
      - "DOCKER_REGISTRY_URL=http://172.20.141.98:30005"
      - "NO_SSL_VERIFICATION=true"
      - "BASIC_AUTH_USER=dockeruser"
      - "BASIC_AUTH_PASSWORD=1qaz2wsx"
      - "ENABLE_DELETE_IMAGES=true"
    ports:
      - "8000:8080"
    restart: always

